version: "3.8"

services:
  db:
    image: postgres:16
    container_name: ems_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: emsdb
      POSTGRES_USER: emsuser
      POSTGRES_PASSWORD: emspassword
    ports:
      - "5432:5432"
    volumes:
      - ems_pgdata:/var/lib/postgresql/data

volumes:
  ems_pgdata:
